import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://imedengb.rd.dtcs.local/im1ws_imedengb/#/login');
  await page.locator('#userName').click();
  await page.locator('#userName').fill('Rupa');
  await page.locator('#userName').press('Tab');
  await page.locator('#password').fill('netcare20');
  await page.locator('#password').press('Tab');
  await page.getByRole('link', { name: '' }).press('Enter');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.goto('https://imedengb.rd.dtcs.local/im1ws_imedengb/#/workplace');
  await page.getByRole('button', { name: '' }).click();
  await page.getByRole('searchbox', { name: 'First Name, Surname, Birth' }).click();
  await page.getByRole('searchbox', { name: 'First Name, Surname, Birth' }).fill('Will');
  await page.getByRole('button', { name: '' }).click();
  await page.getByText('Jack, Will, 10/08/1996 []').click();
  await page.getByRole('button', { name: 'Select', exact: true }).click();
  await page.getByRole('link', { name: ' Orders' }).click();
  await page.getByRole('menuitem', { name: 'Order Entry' }).locator('div').click();
  await page.getByRole('button', { name: 'New Order' }).click();
  await page.getByRole('button', { name: 'Surgery & Procedures' }).click();
  await page.getByRole('link', { name: ' Surgery' }).click();
  await page.getByRole('link', { name: 'Cardiac Surgery ' }).click();
  await page.getByText('Basic Data').click();
  await page.locator('[id="\\30 "] div').filter({ hasText: 'Ward Ordering Doctor Tel.' }).nth(2).click();
  await page.getByRole('button', { name: 'Next ' }).click();
  await page.getByRole('button', { name: 'Release' }).click();
  await page.locator('#password').click();
  await page.locator('#password').fill('netcare20');
  await page.getByRole('button', { name: 'Authenticate' }).click();
  await expect(page.getByRole('heading')).toContainText('Order creation was successful. Following orders are created:');
  await page.getByRole('button', { name: 'Ok' }).click();
  await page.getByRole('link', { name: ' ADT' }).click();
  await page.getByRole('menuitem', { name: 'MedicalCoding' }).locator('div').click();
  await page.getByText('Procedures', { exact: true }).click();
  await page.locator('i1-medicalcoding-container').filter({ hasText: 'Clinical Procedures Remove' }).locator('i1-combo-box #dropdownIcon').click();
  await page.locator('html').click();
  await page.locator('#SearchCodeLevelprocedureContainer').click();
  await page.locator('i1-medicalcoding-container').filter({ hasText: 'Clinical Procedures Remove' }).locator('i1-combo-box #dropdownIcon').click();
  await page.locator('html').click();
  await page.locator('i1-medicalcoding-container').filter({ hasText: 'Clinical Procedures Remove' }).locator('i1-combo-box #dropdownIcon').click();
  await page.locator('#SearchCodeLevelprocedureContainer').fill('3S0007 - General Surgery Speciality - Admission at 10/03/2025 10:16 ');
  await page.locator('#SearchCodeLevelprocedureContainer').press('ControlOrMeta+a');
  await page.locator('#SearchCodeLevelprocedureContainer').fill('');
  await page.locator('i1-medicalcoding-container').filter({ hasText: 'Clinical Procedures Remove' }).locator('i1-combo-box #dropdownIcon').click();
  await page.locator('html').click();
  await page.locator('#SearchCodeLevelprocedureContainer').click();
  await page.locator('#SearchCodeLevelprocedureContainer').fill('Med');
  await page.getByText('MED - General Surgery at 31/').nth(1).click();
  await page.locator('#catalogSelectCombo').click();
  await page.locator('#MedicalCoding i1-catalog-combo #dropdownIcon').click();
  await page.locator('html').click();
  await page.locator('i1-medicalcoding-container').filter({ hasText: 'Clinical Procedures Remove' }).locator('i1-combo-box #dropdownIcon').click();
  await page.locator('html').click();
  await page.locator('i1-medicalcoding-container').filter({ hasText: 'Clinical Procedures Remove' }).locator('span').nth(2).click();
  await page.getByText('MED - General Surgery at 31/').nth(1).click();
  await page.getByText('Remove C23S0007 - General').nth(1).click({
    button: 'right'
  });
  await page.locator('i1-medicalcoding-container').filter({ hasText: 'Clinical Procedures Remove' }).locator('span').nth(2).click();
  await page.locator('#SearchCodeLevelprocedureContainer').click();
  await page.locator('#SearchCodeLevelprocedureContainer').dblclick();
  await page.getByRole('listitem').filter({ hasText: '19508 MED - General Surgery' }).click();
  await page.getByRole('button', { name: 'Ok' }).click();
  await page.locator('#searchCodeprocedureContainer').click();
  await page.locator('#searchCodeprocedureContainer').fill('3100');
  await page.locator('#searchCodeprocedureContainer').press('Enter');
  await page.locator('#newCode').click();
  await page.locator('#codeEditTemplate #dropdownIcon').click();
  await page.getByRole('listitem').filter({ hasText: ': Respiratory System (30000 - 32999)' }).locator('i').nth(1).click();
  await page.locator('treeitem').getByRole('listitem').filter({ hasText: '3-001: Accessory Sinuses:' }).locator('i').nth(1).click();
  await page.locator('#hierarchialCatSearch').click();
  await page.locator('#hierarchialCatSearch').fill('31231');
  await page.getByText('31231: Nasal endoscopy,').click();
  await page.getByRole('button', { name: 'Ok' }).click();
  await page.getByRole('button', { name: 'Main' }).click();
  await page.getByRole('button', { name: 'Additional' }).click();
  await page.getByRole('button', { name: 'Main' }).click();
  await page.getByRole('button', { name: 'Apply' }).click();
  await page.locator('#codeEditTemplate #dropdownIcon').click();
  await page.getByRole('listitem').filter({ hasText: ': Respiratory System (30000 - 32999)' }).locator('i').nth(1).click();
  await page.locator('treeitem').getByRole('listitem').filter({ hasText: '3-001: Accessory Sinuses:' }).locator('i').nth(1).click();
  await page.getByText('31231: Nasal endoscopy,').click();
  await page.getByRole('button', { name: 'Ok' }).click();
  await page.getByRole('link', { name: ' 2 Notification' }).click();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.getByRole('link', { name: ' 2 Notification' }).click();
});