import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://imedengb.rd.dtcs.local/im1ws_imedengb/#/login');
  await page.locator('#userName').click();
  await page.locator('#userName').fill('Rupa');
  await page.locator('#userName').press('Tab');
  await page.locator('#password').fill('netcare20');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: '' }).click();
  await page.getByRole('searchbox', { name: 'First Name, Surname, Birth' }).click();
  await page.getByRole('searchbox', { name: 'First Name, Surname, Birth' }).fill('Will');
  await page.getByRole('button', { name: '' }).click();
  await page.getByText('Jack, Will, 10/08/1996 [] MRN').click();
  await page.getByRole('button', { name: 'Select', exact: true }).click();
  await page.getByRole('link', { name: 'ADT' }).click();
  await page.getByRole('menuitem', { name: 'MedicalCoding' }).locator('div').click();
  await page.locator('i1-medicalcoding-container').filter({ hasText: 'Clinical Diagnoses Remove' }).locator('i1-combo-box #dropdownIcon').click();
  await page.locator('html').click();
  await page.locator('#SearchCodeLevelmedicalCodeContainer').click();
  await page.locator('#SearchCodeLevelmedicalCodeContainer').press('ArrowDown');
  await page.locator('#SearchCodeLevelmedicalCodeContainer').press('ArrowDown');
  await page.locator('i1-medicalcoding-container').filter({ hasText: 'Clinical Diagnoses Remove' }).locator('i1-combo-box #dropdownIcon').click();
  await page.locator('#SearchCodeLevelmedicalCodeContainer').press('ControlOrMeta+a');
  await page.locator('#SearchCodeLevelmedicalCodeContainer').fill('');
  await page.locator('#SearchCodeLevelmedicalCodeContainer').click();
  await page.locator('i1-medicalcoding-container').filter({ hasText: 'Clinical Diagnoses Remove' }).locator('i1-combo-box #dropdownIcon').click();
  await page.locator('#SearchCodeLevelmedicalCodeContainer').press('Enter');
  await page.locator('#SearchCodeLevelmedicalCodeContainer').press('ArrowDown');
  await page.locator('#SearchCodeLevelmedicalCodeContainer').press('ArrowDown');
  await page.locator('#SearchCodeLevelmedicalCodeContainer').press('ArrowDown');
  await page.locator('#SearchCodeLevelmedicalCodeContainer').click();
  await page.locator('#SearchCodeLevelmedicalCodeContainer').press('ControlOrMeta+a');
  await page.locator('#SearchCodeLevelmedicalCodeContainer').fill('Med');
  await page.locator('#SearchCodeLevelmedicalCodeContainer').press('Tab');
  await page.locator('#searchCodemedicalCodeContainer').click();
  await page.locator('#SearchCodeLevelmedicalCodeContainer').click();
  await page.locator('#SearchCodeLevelmedicalCodeContainer').fill('MED');
  await page.locator('#SearchCodeLevelmedicalCodeContainer').press('ArrowDown');
  await page.locator('#SearchCodeLevelmedicalCodeContainer').press('ArrowRight');
  await page.locator('#SearchCodeLevelmedicalCodeContainer').fill('MED ');
  await page.locator('#SearchCodeLevelmedicalCodeContainer').press('CapsLock');
  await page.locator('#SearchCodeLevelmedicalCodeContainer').fill('MED');
  await page.locator('#SearchCodeLevelmedicalCodeContainer').press('Tab');
  await page.locator('#searchCodemedicalCodeContainer').click();
  await page.locator('#SearchCodeLevelmedicalCodeContainer').click();
  await page.locator('i1-medicalcoding-container').filter({ hasText: 'Clinical Diagnoses Remove' }).locator('i1-combo-box #dropdownIcon').click();
  await page.locator('html').click();
  await page.getByText('MED - General Surgery at 31/').nth(1).click();
  await page.locator('i1-medicalcoding-container').filter({ hasText: 'Clinical Diagnoses Remove' }).locator('i1-hierarchical-combo div').nth(1).click();
  await page.locator('i1-medicalcoding-container').filter({ hasText: 'Clinical Diagnoses Remove' }).locator('i1-combo-box #dropdownIcon').click();
  await page.locator('html').click();
  await page.getByText('Procedures', { exact: true }).click();
  await page.locator('#SearchCodeLevelprocedureContainer').click();
  await page.locator('i1-medicalcoding-container').filter({ hasText: 'Clinical Procedures Remove' }).locator('i1-combo-box #dropdownIcon').click();
  await page.locator('#SearchCodeLevelprocedureContainer').press('ControlOrMeta+A');
  await page.locator('#SearchCodeLevelprocedureContainer').fill('');
  await page.locator('#SearchCodeLevelprocedureContainer').click();
  await page.locator('#SearchCodeLevelprocedureContainer').press('Enter');
  await page.locator('i1-medicalcoding-container').filter({ hasText: 'Clinical Procedures Remove' }).locator('i1-combo-box #dropdownIcon').click();
  await page.locator('#SearchCodeLevelprocedureContainer').press('Enter');
  await page.locator('i1-medicalcoding-container').filter({ hasText: 'Clinical Procedures Remove' }).locator('span').nth(2).click();
  await page.getByText('MED - General Surgery at 31/').nth(1).click();
  await page.locator('#SearchCodeLevelprocedureContainer').click();
  await page.locator('#SearchCodeLevelprocedureContainer').press('ControlOrMeta+A');
  await page.locator('#SearchCodeLevelprocedureContainer').fill('');
  await page.locator('#SearchCodeLevelprocedureContainer').press('CapsLock');
  await page.locator('#SearchCodeLevelprocedureContainer').fill('MED');
  await page.locator('#SearchCodeLevelprocedureContainer').press('Tab');
  await page.locator('#searchCodeprocedureContainer').click();
  await page.locator('#MedicalCoding i1-catalog-combo #dropdownIcon').click();
  await page.locator('html').click();
  await page.locator('i1-medicalcoding-container').filter({ hasText: 'Clinical Procedures Remove' }).locator('i1-combo-box #dropdownIcon').click();
  await page.locator('html').click();
  await page.locator('#SearchCodeLevelprocedureContainer').click();
  await page.locator('i1-medicalcoding-container').filter({ hasText: 'Clinical Procedures Remove' }).locator('i1-combo-box #dropdownIcon').click();
  await page.locator('html').click();
  await page.locator('i1-medicalcoding-container').filter({ hasText: 'Clinical Procedures Remove' }).locator('i1-combo-box #dropdownIcon').click();
  await page.locator('html').click();
  await page.locator('body').press('Enter');
  await page.locator('body').press('Enter');
  await page.locator('#SearchCodeLevelprocedureContainer').click();
  await page.locator('#SearchCodeLevelprocedureContainer').press('ControlOrMeta+Enter');
  await page.locator('#SearchCodeLevelprocedureContainer').press('ControlOrMeta+Enter');
  await page.locator('#SearchCodeLevelprocedureContainer').press('ControlOrMeta+Enter');
  await page.locator('#SearchCodeLevelprocedureContainer').fill('MED-');
  await page.locator('#SearchCodeLevelprocedureContainer').press('Tab');
  await page.locator('#catalogSelectCombo').fill('');
  await page.locator('#SearchCodeLevelprocedureContainer').click();
  await page.locator('#SearchCodeLevelprocedureContainer').fill('MED');
  await page.locator('#SearchCodeLevelprocedureContainer').press('Tab');
  await page.locator('i1-medicalcoding-container').filter({ hasText: 'Clinical Procedures Remove' }).locator('i1-hierarchical-combo div').nth(1).click();
  await page.locator('i1-medicalcoding-container').filter({ hasText: 'Clinical Procedures Remove' }).locator('span').nth(2).click();
  await page.locator('i1-medicalcoding-container').filter({ hasText: 'Clinical Procedures Remove' }).locator('span').first().click();
  await page.locator('#SearchCodeLevelprocedureContainer').click();
  await page.getByText('Procedures', { exact: true }).dblclick();
  await page.locator('#SearchCodeLevelprocedureContainer').click();
  await page.locator('#SearchCodeLevelprocedureContainer').fill('C2');
  await page.locator('#SearchCodeLevelprocedureContainer').press('Tab');
  await page.locator('#SearchCodeLevelprocedureContainer').click();
  await page.locator('#SearchCodeLevelprocedureContainer').click();
  await page.locator('#SearchCodeLevelprocedureContainer').press('ArrowRight');
  await page.locator('#SearchCodeLevelprocedureContainer').press('ArrowRight');
  await page.locator('#SearchCodeLevelprocedureContainer').press('ArrowRight');
  await page.locator('#SearchCodeLevelprocedureContainer').press('ArrowRight');
  await page.locator('#SearchCodeLevelprocedureContainer').press('ArrowRight');
  await page.locator('#SearchCodeLevelprocedureContainer').press('ArrowRight');
  await page.locator('#SearchCodeLevelprocedureContainer').press('ArrowRight');
  await page.locator('#SearchCodeLevelprocedureContainer').press('ArrowRight');
  await page.locator('#SearchCodeLevelprocedureContainer').press('ArrowRight');
  await page.locator('#SearchCodeLevelprocedureContainer').press('ArrowRight');
  await page.locator('#SearchCodeLevelprocedureContainer').press('ArrowRight');
  await page.locator('#SearchCodeLevelprocedureContainer').press('ControlOrMeta+a');
  await page.locator('#SearchCodeLevelprocedureContainer').fill('Gene');
  await page.locator('#SearchCodeLevelprocedureContainer').press('Tab');
  await page.locator('#SearchCodeLevelprocedureContainer').click();
  await page.locator('#SearchCodeLevelprocedureContainer').click();
  await page.getByRole('listitem').filter({ hasText: '19508 MED - General Surgery' }).getByRole('checkbox').check();
  await page.getByRole('button', { name: 'Ok' }).click();
  await page.locator('#MedicalCoding i1-catalog-combo #dropdownIcon').click();
  await page.locator('html').click();
  await page.locator('#catalogSelectCombo').click();
  await page.locator('#catalogSelectCombo').fill('CP');
  await page.locator('#catalogSelectCombo').press('Tab');
  await page.locator('#searchCodeprocedureContainer').click();
  await page.locator('#searchCodeprocedureContainer').fill('13101');
  await page.locator('#searchCodeprocedureContainer').press('Tab');
  await page.getByText('Additional AD').click();
  await page.getByRole('button', { name: 'Additional' }).click();
  await page.getByRole('button', { name: 'Additional' }).click();
  await page.getByRole('button', { name: 'Apply' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('link', { name: ' 2 Notification' }).click();
  await page.getByRole('link', { name: ' 2 Notification' }).click();
  await page.getByRole('link', { name: ' 2 Notification' }).click();
  await page.getByRole('link', { name: ' 2 Notification' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('link', { name: ' 3 Notification' }).click();
  await expect(page.locator('i1-error-bag')).toContainText('Error: 1 One procedure must be categorised as Main for Procedure <General Surgery at 31/03/2025 10:24>.');
  await page.getByRole('link', { name: ' 3 Notification' }).click();
});